import type {
  ProspectProvider,
  ProviderSearchInput,
  RawProspect,
} from "@/server/providers/types";

const b2bFixtures: RawProspect[] = [
  {
    companyName: "LatticeFlow AI",
    domain: "latticeflow.example",
    website: "https://latticeflow.example",
    industry: "Artificial intelligence",
    city: "Bengaluru",
    country: "India",
    employeeCount: 84,
    employeeRange: "51–100",
    revenueRange: "$5M–$10M",
    foundedYear: 2021,
    technologies: ["Next.js", "Python", "OpenRouter"],
    keywords: ["AI governance", "enterprise", "growth"],
    fundingStage: "Series A",
    isHiring: true,
    contactName: "Maya Iyer",
    firstName: "Maya",
    lastName: "Iyer",
    title: "Co-founder & CEO",
    seniority: "Executive",
    email: "maya@latticeflow.example",
    linkedinUrl: "https://linkedin.com/in/maya-demo",
    sourceUrl: "https://latticeflow.example/about",
    websiteQuality: 91,
  },
  {
    companyName: "Northstar Revenue",
    domain: "northstar.example",
    website: "https://northstar.example",
    industry: "B2B software",
    city: "Mumbai",
    country: "India",
    employeeCount: 132,
    employeeRange: "101–200",
    revenueRange: "$10M–$25M",
    foundedYear: 2019,
    technologies: ["Salesforce", "HubSpot", "React"],
    keywords: ["revenue intelligence", "sales", "automation"],
    fundingStage: "Series B",
    isHiring: true,
    contactName: "Kabir Mehta",
    firstName: "Kabir",
    lastName: "Mehta",
    title: "VP Revenue",
    seniority: "VP",
    email: "kabir@northstar.example",
    phone: "+91 90000 00001",
    linkedinUrl: "https://linkedin.com/in/kabir-demo",
    sourceUrl: "https://northstar.example/team",
    websiteQuality: 88,
  },
  {
    companyName: "Cobalt Systems",
    domain: "cobalt.example",
    website: "https://cobalt.example",
    industry: "Enterprise software",
    city: "Pune",
    country: "India",
    employeeCount: 57,
    employeeRange: "51–100",
    revenueRange: "$2M–$5M",
    foundedYear: 2020,
    technologies: ["React", "AWS", "PostgreSQL"],
    keywords: ["operations", "workflow", "enterprise"],
    fundingStage: "Seed",
    isHiring: false,
    contactName: "Rhea Shah",
    firstName: "Rhea",
    lastName: "Shah",
    title: "Founder",
    seniority: "Executive",
    email: "rhea@cobalt.example",
    linkedinUrl: "https://linkedin.com/in/rhea-demo",
    sourceUrl: "https://cobalt.example/company",
    websiteQuality: 84,
  },
  {
    companyName: "Orbit Health Cloud",
    domain: "orbit-health.example",
    website: "https://orbit-health.example",
    industry: "Healthcare software",
    city: "Hyderabad",
    country: "India",
    employeeCount: 176,
    employeeRange: "101–200",
    revenueRange: "$10M–$25M",
    foundedYear: 2018,
    technologies: ["Azure", "TypeScript", "Salesforce"],
    keywords: ["healthcare operations", "cloud", "compliance"],
    fundingStage: "Series B",
    isHiring: true,
    contactName: "Arjun Rao",
    firstName: "Arjun",
    lastName: "Rao",
    title: "Chief Growth Officer",
    seniority: "C-suite",
    email: "arjun@orbit-health.example",
    linkedinUrl: "https://linkedin.com/in/arjun-demo",
    sourceUrl: "https://orbit-health.example/leadership",
    websiteQuality: 93,
  },
  {
    companyName: "Paperkite Labs",
    domain: "paperkite.example",
    website: "https://paperkite.example",
    industry: "Marketing technology",
    city: "Gurugram",
    country: "India",
    employeeCount: 38,
    employeeRange: "21–50",
    revenueRange: "$1M–$2M",
    foundedYear: 2022,
    technologies: ["Next.js", "Vercel", "OpenRouter"],
    keywords: ["creative automation", "marketing", "AI"],
    fundingStage: "Seed",
    isHiring: true,
    contactName: "Tara Kapoor",
    firstName: "Tara",
    lastName: "Kapoor",
    title: "CEO",
    seniority: "Executive",
    email: "tara@paperkite.example",
    linkedinUrl: "https://linkedin.com/in/tara-demo",
    sourceUrl: "https://paperkite.example/about",
    websiteQuality: 86,
  },
];

const b2cFixtures: RawProspect[] = [
  {
    displayName: "Demo Consumer 01",
    ageBand: "25-34",
    city: "Mumbai",
    country: "India",
    interests: ["productivity software", "entrepreneurship"],
    email: "consumer01@example.com",
    consentStatus: "GRANTED",
    consentChannels: ["EMAIL"],
    consentCapturedAt: "2026-06-10T10:00:00.000Z",
    consentExpiresAt: "2027-06-10T10:00:00.000Z",
    consentProofReference: "demo-first-party-opt-in-01",
    consentSource: "first_party_signup",
    sourceUrl: "https://example.com/first-party-signup/01",
  },
  {
    displayName: "Demo Consumer 02",
    ageBand: "35-44",
    city: "Pune",
    country: "India",
    interests: ["business education", "technology"],
    email: "consumer02@example.com",
    consentStatus: "GRANTED",
    consentChannels: ["EMAIL"],
    consentCapturedAt: "2026-06-18T10:00:00.000Z",
    consentExpiresAt: "2027-06-18T10:00:00.000Z",
    consentProofReference: "demo-first-party-opt-in-02",
    consentSource: "first_party_signup",
    sourceUrl: "https://example.com/first-party-signup/02",
  },
  {
    displayName: "Demo Consumer 03",
    ageBand: "25-34",
    city: "Bengaluru",
    country: "India",
    interests: ["software", "small business"],
    email: "consumer03@example.com",
    consentStatus: "GRANTED",
    consentChannels: ["EMAIL"],
    consentCapturedAt: "2026-06-21T10:00:00.000Z",
    consentExpiresAt: "2027-06-21T10:00:00.000Z",
    consentProofReference: "demo-first-party-opt-in-03",
    consentSource: "first_party_signup",
    sourceUrl: "https://example.com/first-party-signup/03",
  },
];

export class DemoProspectProvider implements ProspectProvider {
  async search(input: ProviderSearchInput) {
    const source = input.mode === "B2C" ? b2cFixtures : b2bFixtures;
    const items = Array.from(
      { length: Math.min(input.targetCount, 50) },
      (_, index) => {
        const fixture = source[index % source.length] ?? {};
        const cycle = Math.floor(index / source.length);
        if (!cycle) return { ...fixture };
        return input.mode === "B2C"
          ? {
              ...fixture,
              displayName: `${String(fixture.displayName)} ${cycle + 1}`,
              email: `demo-${index}@example.com`,
            }
          : {
              ...fixture,
              companyName: `${String(fixture.companyName)} ${cycle + 1}`,
              domain: `demo-${index}.${String(fixture.domain)}`,
              email: `demo-${index}@${String(fixture.domain)}`,
            };
      },
    );
    return {
      items,
      provenance: {
        sourceType: "DEMO" as const,
        provider: "athreix-demo",
        sourceUrl: "https://example.com/demo-data",
        collectedAt: new Date().toISOString(),
      },
    };
  }
}
