import type {
  ExportRecord,
  Prospect,
  SavedFolder,
  SearchRecord,
} from "./types";

const baseEvidence = [
  {
    label: "Company activity",
    value: "Hiring across revenue and customer success roles",
    source: "Company careers page",
    freshness: "Checked 2 days ago",
    confidence: 94,
  },
  {
    label: "Role evidence",
    value: "Public profile lists this leadership role",
    source: "Public professional profile",
    freshness: "Checked 5 days ago",
    confidence: 91,
  },
  {
    label: "Technology signal",
    value: "Uses HubSpot and Segment",
    source: "Public website technology scan",
    freshness: "Checked 8 days ago",
    confidence: 87,
  },
];

const seeds = [
  [
    "Ananya Rao",
    "Founder & CEO",
    "SignalNest",
    "AI software",
    "Bengaluru, IN",
    96,
    "Review",
    "High",
    "51–200",
  ],
  [
    "Rohan Mehta",
    "VP of Growth",
    "OrbitDesk",
    "SaaS",
    "Mumbai, IN",
    93,
    "Review",
    "High",
    "51–200",
  ],
  [
    "Maya Iyer",
    "Chief Revenue Officer",
    "PostGrid Labs",
    "Developer tools",
    "Pune, IN",
    91,
    "Review",
    "High",
    "201–500",
  ],
  [
    "Kabir Shah",
    "Co-founder",
    "NudgeCart",
    "E-commerce",
    "Ahmedabad, IN",
    89,
    "Review",
    "High",
    "21–50",
  ],
  [
    "Sara Thomas",
    "Head of Marketing",
    "Current Health",
    "Health technology",
    "Hyderabad, IN",
    87,
    "Review",
    "Medium",
    "51–200",
  ],
  [
    "Arjun Malhotra",
    "Revenue Director",
    "Kitepay",
    "Fintech",
    "Gurugram, IN",
    85,
    "Review",
    "Medium",
    "201–500",
  ],
  [
    "Diya Nair",
    "Founder",
    "Studio Alto",
    "Marketing services",
    "Kochi, IN",
    82,
    "Review",
    "Medium",
    "11–20",
  ],
  [
    "Nikhil Bansal",
    "Sales Director",
    "ParseWorks",
    "Data infrastructure",
    "Noida, IN",
    80,
    "Review",
    "Medium",
    "51–200",
  ],
  [
    "Ishita Sen",
    "Chief Operating Officer",
    "CareLoop",
    "Health services",
    "Kolkata, IN",
    78,
    "Review",
    "Medium",
    "201–500",
  ],
  [
    "Dev Khanna",
    "Managing Partner",
    "Northline",
    "Consulting",
    "New Delhi, IN",
    76,
    "Limited",
    "Medium",
    "21–50",
  ],
  [
    "Tara Krishnan",
    "VP, Partnerships",
    "MosaicHR",
    "HR technology",
    "Chennai, IN",
    74,
    "Review",
    "Low",
    "51–200",
  ],
  [
    "Aman Joshi",
    "Growth Lead",
    "FreightFox",
    "Logistics",
    "Jaipur, IN",
    72,
    "Review",
    "Low",
    "51–200",
  ],
  [
    "Meera Kapoor",
    "Founder & CEO",
    "Archway Learning",
    "Education",
    "Chandigarh, IN",
    69,
    "Review",
    "Low",
    "21–50",
  ],
  [
    "Varun Pillai",
    "Head of Demand Generation",
    "CloudMint",
    "Cloud software",
    "Bengaluru, IN",
    67,
    "Review",
    "Low",
    "201–500",
  ],
  [
    "Saanvi Desai",
    "Commercial Director",
    "Form Theory",
    "Manufacturing",
    "Surat, IN",
    64,
    "Limited",
    "Low",
    "501–1,000",
  ],
  [
    "Aditya Bose",
    "General Manager",
    "UrbanOrigin",
    "Consumer goods",
    "Mumbai, IN",
    61,
    "Review",
    "Low",
    "201–500",
  ],
] as const;

export const prospects: Prospect[] = seeds.map((seed, index) => {
  const [
    name,
    title,
    company,
    industry,
    location,
    score,
    status,
    intent,
    companySize,
  ] = seed;
  const slug = `${name}`.toLowerCase().replaceAll(" ", ".");
  return {
    id: `prospect-${index + 1}`,
    mode: "b2b",
    name,
    title,
    company,
    industry,
    location,
    email: `${slug}@${`${company}`.toLowerCase().replaceAll(" ", "")}.example`,
    phone: index % 3 === 0 ? "+91 ••••• ••418" : undefined,
    linkedin: `https://linkedin.com/in/${slug.replaceAll(".", "-")}`,
    website: `https://${`${company}`.toLowerCase().replaceAll(" ", "")}.example`,
    score,
    status: status as Prospect["status"],
    intent: intent as Prospect["intent"],
    companySize,
    decisionConfidence: Math.max(62, score - (index % 5)),
    channel: index % 4 === 0 ? "LinkedIn" : index % 5 === 0 ? "Phone" : "Email",
    summary: `${name} leads ${title.toLowerCase().includes("founder") ? "company strategy" : "commercial growth"} at ${company}, a ${companySize}-person ${industry.toLowerCase()} business showing recent go-to-market activity.`,
    reasons: [
      `${title} is directly connected to the buying decision`,
      `${industry} matches the saved ideal-customer profile`,
      "Recent hiring activity suggests an active growth programme",
      `The ${companySize} employee range fits the preferred delivery model`,
    ],
    offer: `A focused revenue intelligence pilot for ${company}, beginning with pipeline research and a measured outbound workflow.`,
    technologies:
      index % 2 === 0
        ? ["HubSpot", "Segment", "Webflow"]
        : ["Salesforce", "Slack", "AWS"],
    evidence: baseEvidence.map((item, evidenceIndex) => ({
      ...item,
      confidence: Math.max(
        60,
        item.confidence - (index % 4) * 2 - evidenceIndex,
      ),
    })),
  };
});

const consumerSeeds = [
  [
    "Aarohi Verma",
    "Mumbai, IN",
    94,
    "Email",
    "Existing subscriber",
    "Newsletter and research consent",
  ],
  [
    "Vivaan Menon",
    "Pune, IN",
    91,
    "Email",
    "Event attendee",
    "Product research opt-in",
  ],
  [
    "Kiara Sethi",
    "Mumbai, IN",
    89,
    "Phone",
    "Existing customer",
    "Service follow-up consent",
  ],
  [
    "Reyansh Kulkarni",
    "Nashik, IN",
    86,
    "Email",
    "Loyalty member",
    "Member research consent",
  ],
  [
    "Myra Fernandes",
    "Goa, IN",
    83,
    "LinkedIn",
    "Community member",
    "Community research opt-in",
  ],
  [
    "Ayaan Reddy",
    "Hyderabad, IN",
    79,
    "Email",
    "Webinar attendee",
    "Event communications consent",
  ],
  [
    "Navya Jain",
    "Surat, IN",
    76,
    "Email",
    "Existing subscriber",
    "Newsletter and research consent",
  ],
  [
    "Atharv Rao",
    "Bengaluru, IN",
    72,
    "Phone",
    "Existing customer",
    "Service follow-up consent",
  ],
] as const;

export const consumerProspects: Prospect[] = consumerSeeds.map(
  (seed, index) => {
    const [name, location, score, channel, relationship, consent] = seed;
    const slug = name.toLowerCase().replaceAll(" ", ".");
    return {
      id: `consumer-${index + 1}`,
      mode: "b2c",
      name,
      title: relationship,
      company: "First-party audience",
      industry: "Permissioned customer research",
      location,
      email: `${slug}@customer.example`,
      phone: index % 3 === 0 ? "+91 ••••• ••274" : undefined,
      linkedin: "",
      website: "",
      score,
      status: "Review",
      intent: score >= 85 ? "High" : score >= 75 ? "Medium" : "Low",
      companySize: "Not applicable",
      decisionConfidence: Math.max(70, score - 2),
      channel: channel as Prospect["channel"],
      summary: `${name} is an ${relationship.toLowerCase()} in the permissioned first-party audience. The record matches the declared product-research purpose and carries ${consent.toLowerCase()} with a current suppression check.`,
      reasons: [
        `${consent} is attached to the source record`,
        `${relationship} matches the purpose-limited audience definition`,
        "The broad region is within the approved research scope",
        "Suppression and deletion lists were checked before inclusion",
      ],
      offer:
        "A voluntary, clearly described product-research invitation with no penalty for declining and a visible opt-out path.",
      technologies: [],
      evidence: [
        {
          label: "Permission record",
          value: consent,
          source: "First-party consent ledger",
          freshness: "Checked today",
          confidence: 98,
        },
        {
          label: "Audience relationship",
          value: relationship,
          source: "Customer record",
          freshness: "Checked today",
          confidence: 94,
        },
        {
          label: "Suppression status",
          value: "No active deletion or contact suppression",
          source: "Workspace suppression list",
          freshness: "Checked today",
          confidence: 100,
        },
      ],
      consumer: {
        relationship,
        consentStatus: index === 6 ? "Review" : "Confirmed",
        source: "First-party customer record",
        collectedAt: "12 Jul 2026",
        retentionUntil: "19 Aug 2026",
        purpose: "Invite opted-in customers to voluntary product research",
        suppressionChecked: "20 Jul 2026, 10:41",
        allowedChannels: [channel as "Email" | "LinkedIn" | "Phone"],
        permissionExpires: "19 Aug 2026",
      },
    };
  },
);

export const searches: SearchRecord[] = [
  {
    id: "india-saas-founders",
    query: "SaaS founders in India, 20–200 employees, hiring sales",
    mode: "b2b",
    status: "complete",
    count: 248,
    highQuality: 84,
    createdAt: "Today, 10:42",
    owner: "Aryan",
  },
  {
    id: "mumbai-agencies",
    query: "Growth agencies in Mumbai using HubSpot",
    mode: "b2b",
    status: "complete",
    count: 116,
    highQuality: 41,
    createdAt: "Yesterday, 16:18",
    owner: "Aryan",
  },
  {
    id: "consent-retail-audience",
    query: "Opted-in premium retail audience, west India",
    mode: "b2c",
    status: "processing",
    count: 0,
    highQuality: 0,
    createdAt: "Yesterday, 12:06",
    owner: "Priya",
  },
  {
    id: "healthcare-pune",
    query: "Healthcare startups in Pune founded after 2020",
    mode: "b2b",
    status: "complete",
    count: 93,
    highQuality: 28,
    createdAt: "18 Jul, 09:32",
    owner: "Aryan",
  },
  {
    id: "salesforce-manufacturing",
    query: "Manufacturers using Salesforce, 200+ employees",
    mode: "b2b",
    status: "failed",
    count: 0,
    highQuality: 0,
    createdAt: "17 Jul, 14:51",
    owner: "Aryan",
  },
];

export const exports: ExportRecord[] = [
  {
    id: "exp-1048",
    name: "India SaaS — high confidence",
    format: "XLSX",
    records: 84,
    status: "Ready",
    createdAt: "Today, 11:04",
    scope: "Score 80+, source-supported",
    createdBy: "Aryan",
  },
  {
    id: "exp-1047",
    name: "Mumbai agencies — full list",
    format: "CSV",
    records: 116,
    status: "Ready",
    createdAt: "Yesterday, 16:44",
    scope: "All authorized fields",
    createdBy: "Aryan",
  },
  {
    id: "exp-1046",
    name: "Pune healthcare shortlist",
    format: "CSV",
    records: 28,
    status: "Expired",
    createdAt: "12 Jul, 10:14",
    scope: "Selected records",
    createdBy: "Aryan",
  },
  {
    id: "exp-1045",
    name: "CRM import payload",
    format: "JSON",
    records: 61,
    status: "Ready",
    createdAt: "8 Jul, 18:22",
    scope: "Score 75+, source-supported",
    createdBy: "Priya",
  },
];

export const savedFolders: SavedFolder[] = [
  {
    id: "list-priority",
    name: "Q3 priority accounts",
    description: "Owner-reviewed opportunities for this quarter",
    count: 38,
    updatedAt: "Today",
    shared: true,
    prospectIds: prospects.slice(0, 5).map((item) => item.id),
  },
  {
    id: "list-founders",
    name: "Founder-led SaaS",
    description: "India-based, 20–200 people",
    count: 74,
    updatedAt: "Yesterday",
    shared: false,
    prospectIds: prospects.slice(0, 8).map((item) => item.id),
  },
  {
    id: "list-agencies",
    name: "Agency partnerships",
    description: "Potential channel partners in west India",
    count: 29,
    updatedAt: "18 Jul",
    shared: true,
    prospectIds: prospects.slice(5, 12).map((item) => item.id),
  },
  {
    id: "list-review",
    name: "Needs evidence review",
    description: "Promising records with incomplete verification",
    count: 17,
    updatedAt: "15 Jul",
    shared: false,
    prospectIds: prospects
      .filter((item) => item.status === "Review")
      .map((item) => item.id),
  },
];

export const activity = [
  {
    time: "11:04",
    title: "Export ready",
    detail: "84 source-supported SaaS prospects prepared as XLSX",
    kind: "export",
  },
  {
    time: "10:58",
    title: "Scoring finished",
    detail: "248 records ranked; 84 matched your high-confidence rule",
    kind: "ai",
  },
  {
    time: "10:42",
    title: "Search started",
    detail: "SaaS founders in India, 20–200 employees",
    kind: "search",
  },
  {
    time: "09:20",
    title: "List updated",
    detail: "Priya added reviewed prospects to Q3 priority accounts",
    kind: "list",
  },
];

export const jobStages = [
  {
    key: "google",
    label: "Searching Google",
    detail: "Finding companies and public business evidence",
  },
  {
    key: "website",
    label: "Reading website",
    detail: "Crawling the homepage, navigation, and key content",
  },
  {
    key: "contacts",
    label: "Finding contacts",
    detail: "Resolving public decision-maker and contact evidence",
  },
  {
    key: "about",
    label: "Reading about page",
    detail: "Understanding the company, model, and target customers",
  },
  {
    key: "services",
    label: "Finding services",
    detail: "Mapping products, services, and commercial positioning",
  },
  {
    key: "careers",
    label: "Checking careers",
    detail: "Detecting hiring velocity and expansion signals",
  },
  {
    key: "news",
    label: "Checking news",
    detail: "Collecting recent announcements and public activity",
  },
  {
    key: "analysis",
    label: "Analyzing company",
    detail: "Synthesizing website, business, and market intelligence",
  },
  {
    key: "intent",
    label: "Calculating buying intent",
    detail: "Scoring timing, pain, fit, and evidence confidence",
  },
  {
    key: "summary",
    label: "Generating AI summary",
    detail: "Writing a transparent, evidence-backed company brief",
  },
  {
    key: "outreach",
    label: "Generating outreach",
    detail: "Preparing personalized messages and a sales strategy",
  },
] as const;

export const suggestions = [
  "Find revenue leaders at recently funded SaaS companies in India",
  "Review accounts hiring more than five sales roles this month",
  "Build an evidence-backed list from last week’s high-confidence prospects",
];
